"""Initial schema

Revision ID: b46163fca1c8
Revises: 
Create Date: 2026-06-20 23:13:33.169747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b46163fca1c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threat_feed_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('original_url', sa.String(length=2000), nullable=False),
    sa.Column('target_brand', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('lure_type', sa.String(length=100), nullable=True),
    sa.Column('otx_pulse_name', sa.String(length=200), nullable=True),
    sa.Column('urlscan_verdict', sa.String(length=50), nullable=True),
    sa.Column('was_converted', sa.Boolean(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('threat_feed_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_threat_feed_entries_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_threat_feed_entries_ingested_at'), ['ingested_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_threat_feed_entries_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_threat_feed_entries_was_converted'), ['was_converted'], unique=False)

    op.create_table('token_blocklist',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('token_type', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_blocklist_jti'), ['jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_token_blocklist_user_id'), ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('job_role', sa.String(length=80), nullable=True),
    sa.Column('department', sa.String(length=80), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('consent_timestamp', sa.DateTime(), nullable=True),
    sa.Column('cluster_label', sa.String(length=50), nullable=True),
    sa.Column('cluster_assigned_at', sa.DateTime(), nullable=True),
    sa.Column('tour_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=100), nullable=True),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_target_type'), ['target_type'], unique=False)

    op.create_table('awareness_assessments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('phase', sa.String(length=10), nullable=False),
    sa.Column('responses', sa.JSON(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'phase', name='uq_awareness_user_phase')
    )
    with op.batch_alter_table('awareness_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_awareness_assessments_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('body', sa.String(length=480), nullable=True),
    sa.Column('link', sa.String(length=240), nullable=True),
    sa.Column('meta_json', sa.Text(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_read_at'), ['read_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('password_reset_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_requests_approved_by'), ['approved_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_requests_user_id'), ['user_id'], unique=False)

    op.create_table('risk_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('phishing_email_score', sa.Float(), nullable=False),
    sa.Column('smishing_score', sa.Float(), nullable=False),
    sa.Column('vishing_score', sa.Float(), nullable=False),
    sa.Column('physical_security_score', sa.Float(), nullable=False),
    sa.Column('password_hygiene_score', sa.Float(), nullable=False),
    sa.Column('usb_baiting_score', sa.Float(), nullable=False),
    sa.Column('social_engineering_score', sa.Float(), nullable=False),
    sa.Column('data_handling_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('rf_predicted_risk', sa.Float(), nullable=True),
    sa.Column('rf_confidence', sa.Float(), nullable=True),
    sa.Column('shap_summary', sa.JSON(), nullable=True),
    sa.Column('attempts_count', sa.Integer(), nullable=False),
    sa.Column('score_version', sa.Integer(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_scores_risk_level'), ['risk_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_scores_user_id'), ['user_id'], unique=True)

    op.create_table('scenarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('visual_type', sa.String(length=50), nullable=True),
    sa.Column('visual_html', sa.Text(), nullable=True),
    sa.Column('question_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('target_roles', sa.String(length=200), nullable=False),
    sa.Column('correct_answer', sa.String(length=1), nullable=False),
    sa.Column('option_a', sa.String(length=500), nullable=False),
    sa.Column('option_b', sa.String(length=500), nullable=False),
    sa.Column('option_c', sa.String(length=500), nullable=False),
    sa.Column('option_d', sa.String(length=500), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('red_flags', sa.Text(), nullable=True),
    sa.Column('learning_tip', sa.String(length=500), nullable=True),
    sa.Column('tf_statement', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('threat_url', sa.String(length=2000), nullable=True),
    sa.Column('threat_brand', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('times_served', sa.Integer(), nullable=False),
    sa.Column('times_correct', sa.Integer(), nullable=False),
    sa.Column('threat_feed_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['threat_feed_id'], ['threat_feed_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenarios_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_scenarios_difficulty'), ['difficulty'], unique=False)
        batch_op.create_index(batch_op.f('ix_scenarios_target_roles'), ['target_roles'], unique=False)
        batch_op.create_index(batch_op.f('ix_scenarios_threat_feed_id'), ['threat_feed_id'], unique=False)

    op.create_table('sus_responses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('responses', sa.JSON(), nullable=False),
    sa.Column('sus_score', sa.Float(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sus_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sus_responses_user_id'), ['user_id'], unique=False)

    op.create_table('user_clusters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('archetype_label', sa.String(length=100), nullable=False),
    sa.Column('archetype_description', sa.Text(), nullable=False),
    sa.Column('feature_vector', sa.Text(), nullable=False),
    sa.Column('clustered_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_clusters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_clusters_cluster_id'), ['cluster_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_clusters_clustered_at'), ['clustered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_clusters_user_id'), ['user_id'], unique=False)

    op.create_table('attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('answer_given', sa.String(length=1), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempts_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempts_difficulty'), ['difficulty'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempts_is_correct'), ['is_correct'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempts_is_synthetic'), ['is_synthetic'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempts_scenario_id'), ['scenario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempts_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempts_user_id'), ['user_id'], unique=False)

    op.create_table('user_behavior_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_behavior_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_behavior_events_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_behavior_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_behavior_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_behavior_events_scenario_id'), ['scenario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_behavior_events_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_behavior_events_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_behavior_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_behavior_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_behavior_events_session_id'))
        batch_op.drop_index(batch_op.f('ix_user_behavior_events_scenario_id'))
        batch_op.drop_index(batch_op.f('ix_user_behavior_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_user_behavior_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_user_behavior_events_category'))

    op.drop_table('user_behavior_events')
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attempts_user_id'))
        batch_op.drop_index(batch_op.f('ix_attempts_session_id'))
        batch_op.drop_index(batch_op.f('ix_attempts_scenario_id'))
        batch_op.drop_index(batch_op.f('ix_attempts_is_synthetic'))
        batch_op.drop_index(batch_op.f('ix_attempts_is_correct'))
        batch_op.drop_index(batch_op.f('ix_attempts_difficulty'))
        batch_op.drop_index(batch_op.f('ix_attempts_created_at'))
        batch_op.drop_index(batch_op.f('ix_attempts_category'))

    op.drop_table('attempts')
    with op.batch_alter_table('user_clusters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_clusters_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_clusters_clustered_at'))
        batch_op.drop_index(batch_op.f('ix_user_clusters_cluster_id'))

    op.drop_table('user_clusters')
    with op.batch_alter_table('sus_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sus_responses_user_id'))

    op.drop_table('sus_responses')
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenarios_threat_feed_id'))
        batch_op.drop_index(batch_op.f('ix_scenarios_target_roles'))
        batch_op.drop_index(batch_op.f('ix_scenarios_difficulty'))
        batch_op.drop_index(batch_op.f('ix_scenarios_category'))

    op.drop_table('scenarios')
    with op.batch_alter_table('risk_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_scores_user_id'))
        batch_op.drop_index(batch_op.f('ix_risk_scores_risk_level'))

    op.drop_table('risk_scores')
    with op.batch_alter_table('password_reset_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_requests_status'))
        batch_op.drop_index(batch_op.f('ix_password_reset_requests_approved_by'))

    op.drop_table('password_reset_requests')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_type'))
        batch_op.drop_index(batch_op.f('ix_notifications_read_at'))

    op.drop_table('notifications')
    with op.batch_alter_table('awareness_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_awareness_assessments_user_id'))

    op.drop_table('awareness_assessments')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_target_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_target_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_blocklist_user_id'))
        batch_op.drop_index(batch_op.f('ix_token_blocklist_jti'))

    op.drop_table('token_blocklist')
    with op.batch_alter_table('threat_feed_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_threat_feed_entries_was_converted'))
        batch_op.drop_index(batch_op.f('ix_threat_feed_entries_source'))
        batch_op.drop_index(batch_op.f('ix_threat_feed_entries_ingested_at'))
        batch_op.drop_index(batch_op.f('ix_threat_feed_entries_category'))

    op.drop_table('threat_feed_entries')
    # ### end Alembic commands ###
